spring:
  application:
    name: ingestion-gateway

  # Connect to your Docker PostgreSQL database
  datasource:
    url: jdbc:postgresql://localhost:5432/flash_resolve_db
    username: admin
    password: secretpassword
    driver-class-name: org.postgresql.Driver

  # Tell Hibernate to automatically create tables matching our Java objects
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      "[hibernate.format_sql]": true

  # Connect to your Docker Redis instance
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  metrics:
    tags:
      application: ingestion-gateway
