global:
  scrape_interval: 5s # Scrape metrics every 5 seconds for real-time tracking

scrape_configs:
  - job_name: 'spring-boot-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # 'host.docker.internal' allows the Prometheus container to talk to your local Windows machine
      - targets: ['host.docker.internal:8081']